export const Notification = [
  'NotificationMissingFromLocals',
  'NotificationRequestorIdMissing',
  'FailedToDeleteAdminNotification',
  'FailedToSaveNotification',
  'SelfInviteNotAllowed',
  'RecipientEmailMissingFromLocals',
  'RecipientEmailInMemoryCache',
  'RecipientMissingFromLocals',
  'RecipientOrganizationMissingFromLocals',
  'NotificationAlreadyExists',
  'NotificationByIdNotFoundInDb',
  'NotificationRequestorOrganizationIdMissingFromLocals',
  'NotificationRequestorIdMissingFromLocals',
  'NotificationAlreadyDeleted',
] as const;
