export const Organization = [
  'OrganizationByUserIdNotFoundInDb',
  'OrganizationTypeNotSalient',
  'OrganizationTypeNotIntegrator',
  'OrganizationTypeNotEndUser',
  'OrganizationMissingFromLocals',
  'OrganizationByDeploymentIdNotFoundInDb',
  'OrgNotFoundWhenDeregisteringDeployment',
  'OrgConnectionMissingFromLocals',
  'FailedToSaveOrgConnection',
  'OrganizationByIdNotFoundInDb',
  'FailedToDeleteOrgConnection',
  'OrganizationsAlreadyAssociated',
  'OrgConnectionNotFoundInDb',
  'OrganizationHasNoUsers',
  'LastAdminNotAllowedToLeaveOrg',
] as const;
