export const Shared = [
  'ValidationError',
  'UndefinedParam',
  'InvalidSubsetSelection',
  'ParamQueryNull',
  'ParamQueryError',
  'SubParamNotFound',
  'EmailDeliveryFailure',
  'ReadNotPermitted',
  'DeleteNotPermitted',
  'UpdateNotPermitted',
  'CreateNotPermitted',
  'UpdateQueryResultUndefined',
  'RecipientEmailMissingFromLocals',
  'RecipientMissingFromLocals',
  'SuspiciousRequestor',
  'FailedToUpdateObject',
  'MongooseCriticalError',
  'BcryptError',
] as const;
